condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
newline_style = "Unix"
